# <font style="color:rgb(0,0,0);"> 简介 </font>
<font style="color:rgb(0,0,0);">程序中出现某些异常的状况的时候，异常就发生了。例如，想要读某个文件的时候，而那个文件不存在。或者在程序运行的时候，不小心把它删除了。 </font>

<font style="color:rgb(0,0,0);">上述这些情况可以使用异常来处理。 </font>

<font style="color:rgb(0,0,0);">假如程序中有一些无效的语句，会怎么样呢？Python 会引发并告诉你那里有一个错误，从而处理这样的情况。 </font>

# <font style="color:rgb(0,0,0);"> 错误 </font>
<font style="color:rgb(0,0,0);">考虑一个简单的 print 语句。假如我们把 print 误拼为 Print，注意大写，这样Python 会引发一个语法错误。 </font>

```bash
>>> Print("Hello World")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Print' is not defined
>>> print("Hello World")
Hello World
```

<font style="color:rgb(0,0,0);">我们可以观察到有一个 NameError 被引发，并且检测到的错误位置也被打印了出来。这是这个错误的错误处理器所做的工作。 </font>

# <font style="color:rgb(0,0,0);"> 异常 </font>
<font style="color:rgb(0,0,0);">我们尝试读取用户的一段输入。按 </font><font style="color:rgb(0,0,0);">Ctrl-d</font><font style="color:rgb(0,0,0);">，看一下会发生什么。 </font>

```bash
>>> s = input('Enter something --> ')
Enter something --> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
EOFError
```

<font style="color:rgb(0,0,0);">Python 引发了一个称为 EOFError 的错误，这个错误基本上意味着它发现一个不期望的文件尾（由 Ctrl-d 表示）（译者注：Python3.2 中没有此种错误发生） </font>

# <font style="color:rgb(0,0,0);"> 处理异常 </font>
<font style="color:rgb(0,0,0);">我们可以使用 </font>`<font style="color:rgb(0,0,0);">try..except</font>`<font style="color:rgb(0,0,0);"> 语句来处理异常。我们把通常的语句放在</font>`<font style="color:rgb(0,0,0);"> try-</font>`<font style="color:rgb(0,0,0);">块中，而把我们的错误处理语句放在</font>`<font style="color:rgb(0,0,0);"> except-</font>`<font style="color:rgb(0,0,0);">块中。 </font>

```bash
# !/usr/bin/python 
# Filename: try_except.py 
try:
    text = input('Enter something --> ')
except EOFError:
    print('Why did you do an EOF on me?')
except KeyboardInterrupt:
    print('You cancelled the operation.')
else:
    print('You entered {}'.format(text))
```

<font style="color:rgb(0,0,0);">输出： </font>

```bash
# Press ctrl + d
$ python exceptions_handle.py
Enter something --> Why did you do an EOF on me?

# Press ctrl + c
$ python exceptions_handle.py
Enter something --> ^CYou cancelled the operation.

$ python exceptions_handle.py
Enter something --> No exceptions
You entered No exceptions
```

<font style="color:rgb(0,0,0);">如何工作： </font>

<font style="color:rgb(0,0,0);">我们把所有可能引发错误的语句放在 try 块中，然后在 except 从句/块中处理所有的错误和异常。except 从句可以专门处理单一的错误或异常，或者一组包括在圆括号内的错误/异常。如果没有给出错误或异常的名称，它会处理所有的错误和异常。 </font>

<br/>color2
<font style="color:rgb(0,0,0);">注意：对于每个 try 从句，至少都有一个相关联的 except 从句。如果某个错误或异常没有被处理，默认的 Python 处理器就会被调用。它会终止程序的运行，并且打印一个消息，我们已经看到了这样的处理。 </font>

<br/>

<font style="color:rgb(0,0,0);">你还可以让</font>`<font style="color:rgb(0,0,0);"> try..except </font>`<font style="color:rgb(0,0,0);">块关联上一个 else 从句。当没有异常发生的时候，else 从句将被执行。 我们还可以得到异常对象，从而获取更多有个这个异常的信息。这会在下一个例子中说明。 </font>

# <font style="color:rgb(0,0,0);"> 引发异常 </font>
<font style="color:rgb(0,0,0);">你可以使用 </font>`<font style="color:rgb(0,0,0);">raise</font>`<font style="color:rgb(0,0,0);"> 语句引发异常。你还得指明错误/异常的名称和伴随异常触发的异常对象。 </font>

<font style="color:rgb(0,0,0);">你可以引发的错误或异常应该分别是一个 </font>`<font style="color:rgb(0,0,0);">Error</font>`<font style="color:rgb(0,0,0);"> 或 </font>`<font style="color:rgb(0,0,0);">Exception</font>`<font style="color:rgb(0,0,0);"> 类的直接或间接导出类。 </font>

```bash
class ShortInputException(Exception):
    '''A user-defined exception class.'''
    def __init__(self, length, atleast):
        Exception.__init__(self)
        self.length = length
        self.atleast = atleast

try:
    text = input('Enter something --> ')
    if len(text) < 3:
        raise ShortInputException(len(text), 3)
    # Other work can continue as usual here
except EOFError:
    print('Why did you do an EOF on me?')
except ShortInputException as ex:
    print(('ShortInputException: The input was ' +
           '{0} long, expected at least {1}')
          .format(ex.length, ex.atleast))
else:
    print('No exception was raised.')
```

<font style="color:rgb(0,0,0);">输出： </font>

<font style="color:rgb(0,0,0);">这里，我们创建了我们自己的异常类型，其实我们可以使用任何预定义的异常/错误。这个新的异常类型是 </font>`<font style="color:rgb(0,0,0);">ShortInputException</font>`<font style="color:rgb(0,0,0);"> 类。它有两个域——</font>`<font style="color:rgb(0,0,0);">length</font>`<font style="color:rgb(0,0,0);"> 是给定输入的长度，</font>`<font style="color:rgb(0,0,0);">atleast</font>`<font style="color:rgb(0,0,0);"> 则是程序期望的最小长度。 </font>

```bash
$ python exceptions_raise.py
Enter something --> a
ShortInputException: The input was 1 long, expected at least 3

$ python exceptions_raise.py
Enter something --> abc
No exception was raised.
```

<font style="color:rgb(0,0,0);">在 except 从句中，我们提供了错误类和用来表示错误/异常对象的变量。这与函数调用中的形参和实参概念类似。在这个特别的 except 从句中，我们使用异常对象的 length 和 atleast 域来为用户打印一个恰当的消息。 </font>

# <font style="color:rgb(0,0,0);">Try..Finally </font>
<font style="color:rgb(0,0,0);">假如你在读一个文件的时候，希望在无论异常发生与否的情况下都关闭文件，该怎么做呢？</font>

<font style="color:rgb(0,0,0);">这可以使用 </font>`<font style="color:rgb(0,0,0);">finally</font>`<font style="color:rgb(0,0,0);"> 块来完成。注意，在一个 </font>`<font style="color:rgb(0,0,0);">try</font>`<font style="color:rgb(0,0,0);"> 块下，你可以同时使用</font>`<font style="color:rgb(0,0,0);">except</font>`<font style="color:rgb(0,0,0);"> 从句和 </font>`<font style="color:rgb(0,0,0);">finally</font>`<font style="color:rgb(0,0,0);">  块。如果你要同时使用它们的话，需要把一个嵌入另外一个。 </font>

```bash
# !/usr/bin/python 
# Filename: finally.py 
import sys
import time

f = None
try:
    f = open("poem.txt")
    # Our usual file-reading idiom
    while True:
        line = f.readline()
        if len(line) == 0:
            break
        print(line, end='')
        sys.stdout.flush()
        print("Press ctrl+c now")
        # To make sure it runs for a while
        time.sleep(2)
except IOError:
    print("Could not find file poem.txt")
except KeyboardInterrupt:
    print("!! You cancelled the reading from the file.")
finally:
    if f:
        f.close()
    print("(Cleaning up: Closed the file)")
```

<font style="color:rgb(0,0,0);">输出： </font>

<font style="color:rgb(0,0,0);">我们进行通常的读文件工作，但是我有意在每打印一行之前用 </font>`<font style="color:rgb(0,0,0);">time.sleep</font>`<font style="color:rgb(0,0,0);"> 方法暂停 2 秒钟。这样做的原因是让程序运行得慢一些（Python 由于其本质通常运行得很快）。在程序运行的时候，按 Ctrl-c 中断/取消程序。 </font>

```bash
$ python finally.py
Programming is fun
Press ctrl+c now
^C!! You cancelled the reading from the file.
(Cleaning up: Closed the file)
```

<font style="color:rgb(0,0,0);">我们可以观察到 </font>`<font style="color:rgb(0,0,0);">KeyboardInterrupt</font>`<font style="color:rgb(0,0,0);"> 异常被触发，程序退出。但是在程序退出之前，</font>`<font style="color:rgb(0,0,0);">finally</font>`<font style="color:rgb(0,0,0);"> 从句仍然被执行，把文件关闭。 </font>

# <font style="color:rgb(0,0,0);"> with 语句 </font>
<font style="color:rgb(0,0,0);">在 try 块中获得资源，随后又在 </font>`<font style="color:rgb(0,0,0);">finally</font>`<font style="color:rgb(0,0,0);">  块中释放资源，这是一种常见的模式。今后，也有一种 </font>`<font style="color:rgb(0,0,0);">with</font>`<font style="color:rgb(0,0,0);"> 语句能以清晰的方式完成这样的功能。 </font>

```bash
# !/usr/bin/python 
# Filename: using_with.py 

with open("poem.txt") as f:
    for line in f:
        print(line, end='')
```

<font style="color:rgb(0,0,0);">如何工作： </font>

<font style="color:rgb(0,0,0);">输出与前面例子的输出应该一样。这里的区别就是用 with 语句使用 open 函数 ：用 with open 就能使得在结束的时候自动关闭文件。 </font>

<font style="color:rgb(0,0,0);">在屏幕后面发生的事情就是 with 语句使用了一种协议。获得了 open 语句返回的对象，就叫做’thefifile’ 好了。 </font>

<font style="color:rgb(0,0,0);">在启动代码块之前，在后台总会调用 thefifile.__enter__ 函数，在代码块结束后又会调用 thefifile.__exit__ 函数。 </font>

<font style="color:rgb(0,0,0);">所以我们用 fifinally 块写的代码应该自行注意 __exit__ 方法。这就能帮助我们避免反复使用显式的 try..fifinally 语句。 </font>

<font style="color:rgb(0,0,0);">更多关于这一主题的讨论已经超出了本书的范围，所以请参考 </font>[PEP 343](https://peps.python.org/pep-0343/)<font style="color:rgb(0,0,0);">获取综合性的说明。 </font>





